"""
Contains py3Dmol-related functions.
"""

import base64
import time
from pathlib import Path

import py3Dmol
import requests
from ipywidgets import AppLayout, Layout, Output, Select
from IPython.display import display, HTML
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import colors
import numpy as np
import pandas as pd

# Settings:
mpl.rcParams["figure.dpi"] = 300
mpl.rcParams["agg.path.chunksize"] = 10000


def _hex_color(rgb):
    """Convert an [r, g, b] float list (0-1) to a '#rrggbb' hex string for py3Dmol."""
    return "#{:02x}{:02x}{:02x}".format(
        int(rgb[0] * 255), int(rgb[1] * 255), int(rgb[2] * 255)
    )


def _read_content(input_value, ext=None):
    """Read local file content and infer/keep extension."""
    input_value = Path(input_value)
    with open(input_value) as f:
        content = f.read()
    ext = ext or input_value.suffix.strip(".")
    return content, ext


def protein(input_type, input_value, output_image_filename=None):
    """
    Visualizing protein data.

    Parameters
    ----------
    input_type : str
        Either "pdb_code" or a file extension e.g. "pdb".
    input_value : str or pathlib.Path
        Either the PDB code of the protein or a local filepath.
    output_image_filename : str
        Optional; default: None.
        Filename to save a static image of the protein.

    Returns
    -------
    py3Dmol.view
        Interactive py3Dmol viewer visualizing a given protein and (if available) its
        co-crystallized ligand.
    """
    viewer = py3Dmol.view(width=800, height=600)

    if input_type == "pdb_code":
        pdb_data = requests.get(f"https://files.rcsb.org/download/{input_value.upper()}.pdb").text
        viewer.addModel(pdb_data, "pdb")
    else:
        content, ext = _read_content(input_value, input_type)
        viewer.addModel(content, ext)

    viewer.setStyle({"hetflag": False}, {"cartoon": {"color": "spectrum"}})
    viewer.setStyle(
        {"hetflag": True, "not": {"resn": "HOH"}}, {"stick": {}, "sphere": {"scale": 0.25}}
    )
    viewer.zoomTo({"hetflag": False})
    viewer.show()

    if output_image_filename is not None:
        png_data = viewer.png()
        # png() returns a data URI like "data:image/png;base64,...."
        header, encoded = png_data.split(",", 1)
        with open(Path(output_image_filename).with_suffix(".png"), "wb") as f:
            f.write(base64.b64decode(encoded))

    return viewer


def binding_site(protein_input_type, protein_input_value, ccp4_filepath):
    """
    Visualize a binding pocket in 3D using the pocket's residue PDB file.

    Parameters
    ----------
    protein_input_type : str
        Either "pdb_code" or a file extension e.g. "pdb".
    protein_input_value : str or pathlib.Path
        Either the PDB code of the protein, or a local filepath.
    ccp4_filepath : str
        Local filepath (without extension) of the pocket data.
        A corresponding `.pdb` file with the same base name is expected
        alongside the `.ccp4` file (as generated by DoGSiteScorer).

    Returns
    -------
    py3Dmol.view
        Interactive py3Dmol viewer visualizing the selected pocket at its respective position.
    """
    viewer = py3Dmol.view(width=800, height=600)

    if protein_input_type == "pdb_code":
        pdb_data = requests.get(
            f"https://files.rcsb.org/download/{protein_input_value.upper()}.pdb"
        ).text
        viewer.addModel(pdb_data, "pdb")
    else:
        content, ext = _read_content(protein_input_value, protein_input_type)
        viewer.addModel(content, ext)

    viewer.setStyle({"hetflag": False}, {"cartoon": {"color": "spectrum"}})
    viewer.setStyle({"hetflag": True, "not": {"resn": "HOH"}}, {"stick": {}})

    # Load the pocket's PDB file (same base name as the .ccp4 file) instead of the raw CCP4 grid
    pocket_pdb_path = Path(ccp4_filepath).with_suffix(".pdb")
    with open(pocket_pdb_path) as f:
        pocket_pdb_data = f.read()

    viewer.addModel(pocket_pdb_data, "pdb")
    viewer.setStyle(
        {"model": 1}, {"sphere": {"color": "orange", "opacity": 0.5, "scale": 0.3}}
    )

    viewer.zoomTo()
    viewer.show()

    return viewer


def docking(
    protein_filepath,
    list_docking_poses_filepaths,
    list_docking_poses_labels,
    list_docking_poses_affinities,
):
    """
    Visualize a list of docking poses in the protein structure, using py3Dmol.

    Parameters
    ----------
    protein_filepath : str or pathlib.Path
        Filepath of the extracted protein structure used in docking experiment.
    list_docking_poses_filepaths : list of str or pathlib.Path
        List of filepaths for the separated docking poses.
    list_docking_poses_labels : list of str
        List of labels for docking poses to be used for the selection menu.
    list_docking_poses_affinities : list of str or float
        List of binding affinities in kcal/mol, to be viewed for each docking pose.

    Returns
    -------
    ipywidgets.AppLayout
        Interactive layout containing the protein structure and all docking poses,
        with a menu to select between docking poses.
    """
    print("Docking modes")
    print("(CID - mode)")

    protein_filepath = Path(protein_filepath)
    with open(protein_filepath) as f:
        protein_content = f.read()
    protein_ext = protein_filepath.suffix.strip(".")

    list_docking_poses_affinities = list(
        map(lambda x: f"{x} kcal/mol", list_docking_poses_affinities)
    )

    out = Output()

    selector = Select(
        options=[(label, i) for (i, label) in enumerate(list_docking_poses_labels, 1)],
        description="",
        rows=len(list_docking_poses_filepaths) if len(list_docking_poses_filepaths) <= 52 else 52,
        layout=Layout(flex="flex-grow", width="auto"),
    )

    def _on_selection_change(change):
        if change["name"] == "value" and (change["new"] != change["old"]):
            idx = change["new"] - 1
            pose_path = Path(list_docking_poses_filepaths[idx])
            with open(pose_path) as f:
                pose_content = f.read()
            pose_ext = pose_path.suffix.strip(".")
            affinity_label = list_docking_poses_affinities[idx]

            viewer = py3Dmol.view(width=1000, height=600)
            viewer.addModel(protein_content, protein_ext)  # model 0 = protein
            viewer.setStyle({"model": 0}, {"cartoon": {"color": "lightgrey"}})

            viewer.addModel(pose_content, pose_ext)  # model 1 = selected ligand
            viewer.setStyle({"model": 1}, {"stick": {"colorscheme": "greenCarbon"}})
            viewer.addLabel(
                str(affinity_label),
                {"backgroundColor": "black", "fontColor": "white", "backgroundOpacity": 0.8},
                {"model": 1, "index": 0},
            )

            # Show sidechains/licorice around the ligand (equivalent to _RESIDUES_AROUND JS)
            viewer.setStyle(
                {"model": 0, "within": {"distance": 6, "sel": {"model": 1}}},
                {"cartoon": {"color": "lightgrey"}, "stick": {}},
            )

            viewer.zoomTo({"model": 1})

            out.clear_output(wait=True)
            with out:
                display(HTML(viewer._make_html()))

    selector.observe(_on_selection_change)
    display(AppLayout(left_sidebar=selector, center=out, pane_widths=[1, 6, 1]))
    _on_selection_change({"name": "value", "new": 1, "old": None})

    return out


def interactions(
    protein_filepath,
    list_docking_poses_filepaths,
    list_docking_poses_labels,
    list_docking_poses_affinities,
    list_docking_poses_plip_dicts,
):
    """
    Visualize protein-ligand interactions.

    Parameters
    ----------
    protein_filepath : str or pathlib.Path
        Filepath of the extracted protein structure used in docking experiment.
    list_docking_poses_filepaths : list of str or pathlib.Path
        List of filepaths for the separated docking poses.
    list_docking_poses_labels : list of str
        List of labels for docking poses to be used for the selection menu.
    list_docking_poses_affinities : list of str or float
        List of binding affinities in kcal/mol, to be viewed for each docking pose.
    list_docking_poses_plip_dicts : list of dicts
        List of interaction data (as a dict) for each ligand, generated by plip.

    Returns
    -------
    ipywidgets.AppLayout
        Interactive layout containing the protein structure, all docking poses, and the
        interactions between them, with a menu to select between docking poses.
    """
    color_map = {
        "hydrophobic": [0.90, 0.10, 0.29],
        "hbond": [0.26, 0.83, 0.96],
        "waterbridge": [1.00, 0.88, 0.10],
        "saltbridge": [0.67, 1.00, 0.76],
        "pistacking": [0.75, 0.94, 0.27],
        "pication": [0.27, 0.60, 0.56],
        "halogen": [0.94, 0.20, 0.90],
        "metal": [0.90, 0.75, 1.00],
    }

    selector = Select(
        options=[(label, i) for (i, label) in enumerate(list_docking_poses_labels, 1)],
        description="",
        rows=len(list_docking_poses_filepaths) if len(list_docking_poses_filepaths) <= 52 else 52,
        layout=Layout(flex="flex-grow", width="auto"),
    )

    out = Output()

    # Show color-map (unchanged from original — pure matplotlib, no NGLview dependency)
    fig, axs = plt.subplots(nrows=2, ncols=4, figsize=(12, 1))
    plt.subplots_adjust(hspace=1)
    fig.suptitle("Color-map of interactions", size=10, y=1.3)
    for ax, (interaction, color) in zip(fig.axes, color_map.items()):
        ax.imshow(np.zeros((1, 5)), cmap=colors.ListedColormap(color_map[interaction]))
        ax.set_title(interaction, loc="center", fontsize=10)
        ax.set_axis_off()
    plt.show()

    list_docking_poses_affinities = list(
        map(lambda x: f"{x} kcal/mol", list_docking_poses_affinities)
    )

    protein_filepath = Path(protein_filepath)
    with open(protein_filepath) as f:
        protein_content = f.read()
    protein_ext = protein_filepath.suffix.strip(".")

    def _on_selection_change(change):
        if change["name"] == "value" and (change["new"] != change["old"]):
            idx = change["new"]

            viewer = py3Dmol.view(width=1000, height=600)
            viewer.addModel(protein_content, protein_ext)  # model 0 = protein
            viewer.setStyle({"model": 0}, {"cartoon": {"color": "lightgrey"}})
            time.sleep(0.1)

            pose_path = Path(list_docking_poses_filepaths[idx])
            with open(pose_path) as f:
                pose_content = f.read()
            pose_ext = pose_path.suffix.strip(".")

            viewer.addModel(pose_content, pose_ext)  # model 1 = selected ligand
            viewer.setStyle({"model": 1}, {"stick": {"colorscheme": "greenCarbon"}})
            viewer.addLabel(
                str(list_docking_poses_affinities[idx]),
                {"backgroundColor": "black", "fontColor": "white", "backgroundOpacity": 0.8},
                {"model": 1, "index": 0},
            )
            time.sleep(0.1)
            viewer.zoomTo({"model": 1})

            # Interactions
            plip_interactions = list_docking_poses_plip_dicts[idx]
            if isinstance(plip_interactions, list):
                if len(plip_interactions) == 1:
                    plip_interactions = plip_interactions[0]
                else:
                    raise ValueError(
                        "Contact TeachOpenCADD maintainers "
                        "to check the temporary workaround on the interactions dict/list."
                    )

            interacting_residues = []

            for interaction_type, interaction_list in plip_interactions.items():
                color = _hex_color(color_map[interaction_type])

                if len(interaction_list) == 1:
                    continue
                df_interactions = pd.DataFrame.from_records(
                    interaction_list[1:], columns=interaction_list[0]
                )
                for _, interaction in df_interactions.iterrows():
                    lig_coo = interaction["LIGCOO"]
                    prot_coo = interaction["PROTCOO"]
                    viewer.addCylinder(
                        {
                            "start": {"x": lig_coo[0], "y": lig_coo[1], "z": lig_coo[2]},
                            "end": {"x": prot_coo[0], "y": prot_coo[1], "z": prot_coo[2]},
                            "radius": 0.1,
                            "color": color,
                            "label": interaction_type,
                        }
                    )
                    interacting_residues.append(int(interaction["RESNR"]))

            # Display interacting residues (equivalent to add_ball_and_stick calls)
            for resnr in set(interacting_residues):
                viewer.setStyle(
                    {"model": 0, "resi": resnr, "atom": ["C"]},
                    {"stick": {"colorscheme": "chainHetatm", "radius": 0.2}},
                )
                viewer.setStyle(
                    {"model": 0, "resi": resnr, "atom": ["O", "N", "S"]},
                    {"stick": {"colorscheme": "default", "radius": 0.2}},
                )

            out.clear_output(wait=True)
            with out:
                display(HTML(viewer._make_html()))

    selector.observe(_on_selection_change)
    app = AppLayout(left_sidebar=selector, center=out, pane_widths=[1, 6, 1])
    display(app)
    _on_selection_change({"name": "value", "new": 1, "old": None})

    return app